//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureGeneratorProgram.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class de {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal de() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureGeneratorProgram.Resources.Languages.de", typeof(de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        public static string buttonfinish {
            get {
                return ResourceManager.GetString("buttonfinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                               z.B., Finanzen.
        /// </summary>
        public static string hintdepartment {
            get {
                return ResourceManager.GetString("hintdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                    z.B., 1234 1234567.
        /// </summary>
        public static string hintmobile {
            get {
                return ResourceManager.GetString("hintmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                        z.B., Stefan Müller.
        /// </summary>
        public static string hintname {
            get {
                return ResourceManager.GetString("hintname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                    z.B., 123 12345678.
        /// </summary>
        public static string hintphone {
            get {
                return ResourceManager.GetString("hintphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                            z.B., Buchhalter.
        /// </summary>
        public static string hintposition {
            get {
                return ResourceManager.GetString("hintposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abteilung.
        /// </summary>
        public static string labeldepartment {
            get {
                return ResourceManager.GetString("labeldepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handynummer.
        /// </summary>
        public static string labelmobile {
            get {
                return ResourceManager.GetString("labelmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string labelname {
            get {
                return ResourceManager.GetString("labelname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string labeloptional {
            get {
                return ResourceManager.GetString("labeloptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        public static string labelphone {
            get {
                return ResourceManager.GetString("labelphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string labelposition {
            get {
                return ResourceManager.GetString("labelposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzername.
        /// </summary>
        public static string labelusername {
            get {
                return ResourceManager.GetString("labelusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Outlook-Signatur wurde erfolgreich generiert.
        ///Bitte starten Sie Outlook neu..
        /// </summary>
        public static string msgdone {
            get {
                return ResourceManager.GetString("msgdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string msgdonecaption {
            get {
                return ResourceManager.GetString("msgdonecaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msgerrorcaption {
            get {
                return ResourceManager.GetString("msgerrorcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook-Konto nicht gefunden.
        ///Melden Sie sich bei Outlook an und versuchen Sie es erneut..
        /// </summary>
        public static string msgerrornooutlookaccount {
            get {
                return ResourceManager.GetString("msgerrornooutlookaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook nicht gefunden.
        ///Bitte stellen Sie sicher, dass Outlook installiert ist..
        /// </summary>
        public static string msgerrornooutlookprogram {
            get {
                return ResourceManager.GetString("msgerrornooutlookprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie alle erforderlichen Felder aus..
        /// </summary>
        public static string msgerrorrequiredfields {
            get {
                return ResourceManager.GetString("msgerrorrequiredfields", resourceCulture);
            }
        }
    }
}
