//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureGeneratorProgram.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureGeneratorProgram.Resources.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string department {
            get {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                e.g., Finance.
        /// </summary>
        public static string hintdepartment {
            get {
                return ResourceManager.GetString("hintdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                   e.g., 555 1234 5678.
        /// </summary>
        public static string hintmobile {
            get {
                return ResourceManager.GetString("hintmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                           e.g., John Smith.
        /// </summary>
        public static string hintname {
            get {
                return ResourceManager.GetString("hintname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                       e.g., 555 123 456.
        /// </summary>
        public static string hintphone {
            get {
                return ResourceManager.GetString("hintphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                          e.g., Accountant.
        /// </summary>
        public static string hintposition {
            get {
                return ResourceManager.GetString("hintposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number.
        /// </summary>
        public static string mobile {
            get {
                return ResourceManager.GetString("mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Outlook signature has been successfully generated.\nPlease restart Outlook..
        /// </summary>
        public static string msgdone {
            get {
                return ResourceManager.GetString("msgdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string msgdonecaption {
            get {
                return ResourceManager.GetString("msgdonecaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string msgerrorcaption {
            get {
                return ResourceManager.GetString("msgerrorcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook account not found.\nPlease log in to Outlook and then try again..
        /// </summary>
        public static string msgerrornooutlookaccount {
            get {
                return ResourceManager.GetString("msgerrornooutlookaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlook not found.\nPlease make sure Outlook is installed..
        /// </summary>
        public static string msgerrornooutlookprogram {
            get {
                return ResourceManager.GetString("msgerrornooutlookprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out all required fields..
        /// </summary>
        public static string msgerrorrequiredfields {
            get {
                return ResourceManager.GetString("msgerrorrequiredfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string optional {
            get {
                return ResourceManager.GetString("optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string position {
            get {
                return ResourceManager.GetString("position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
    }
}
