//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureGeneratorProgram.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class hu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal hu() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureGeneratorProgram.Resources.Languages.hu", typeof(hu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kész.
        /// </summary>
        public static string buttonfinish {
            get {
                return ResourceManager.GetString("buttonfinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                  pl. Pénzügy.
        /// </summary>
        public static string hintdepartment {
            get {
                return ResourceManager.GetString("hintdepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                          pl. 30 123 4567.
        /// </summary>
        public static string hintmobile {
            get {
                return ResourceManager.GetString("hintmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                          pl. Kovács János.
        /// </summary>
        public static string hintname {
            get {
                return ResourceManager.GetString("hintname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                         e.g., 22 530 123.
        /// </summary>
        public static string hintphone {
            get {
                return ResourceManager.GetString("hintphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                 pl. Könyvelő.
        /// </summary>
        public static string hintposition {
            get {
                return ResourceManager.GetString("hintposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Részleg.
        /// </summary>
        public static string labeldepartment {
            get {
                return ResourceManager.GetString("labeldepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobiltelefonszám.
        /// </summary>
        public static string labelmobile {
            get {
                return ResourceManager.GetString("labelmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Név.
        /// </summary>
        public static string labelname {
            get {
                return ResourceManager.GetString("labelname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nem kötelező.
        /// </summary>
        public static string labeloptional {
            get {
                return ResourceManager.GetString("labeloptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonszám.
        /// </summary>
        public static string labelphone {
            get {
                return ResourceManager.GetString("labelphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beosztás.
        /// </summary>
        public static string labelposition {
            get {
                return ResourceManager.GetString("labelposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév.
        /// </summary>
        public static string labelusername {
            get {
                return ResourceManager.GetString("labelusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elkészült az új Outlook aláírásod.
        ///Kérlek indítsd újra az Outlookot..
        /// </summary>
        public static string msgdone {
            get {
                return ResourceManager.GetString("msgdone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kész.
        /// </summary>
        public static string msgdonecaption {
            get {
                return ResourceManager.GetString("msgdonecaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiba.
        /// </summary>
        public static string msgerrorcaption {
            get {
                return ResourceManager.GetString("msgerrorcaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az Outlook fiók nem található.
        ///Kérlek jelentkezz be az Outlookba, majd próbáld újra..
        /// </summary>
        public static string msgerrornooutlookaccount {
            get {
                return ResourceManager.GetString("msgerrornooutlookaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Az Outlook nem található.
        ///Kérlek bizonyosodj meg róla, hogy az Outlook fel van telepítve a számítógépre..
        /// </summary>
        public static string msgerrornooutlookprogram {
            get {
                return ResourceManager.GetString("msgerrornooutlookprogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kérlek tölsd ki az összes kötelező mezőt..
        /// </summary>
        public static string msgerrorrequiredfields {
            get {
                return ResourceManager.GetString("msgerrorrequiredfields", resourceCulture);
            }
        }
    }
}
