//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignatureGeneratorProgram.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignatureGeneratorProgram.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;a:clrMap xmlns:a=&quot;http://schemas.openxmlformats.org/drawingml/2006/main&quot; bg1=&quot;lt1&quot; tx1=&quot;dk1&quot; bg2=&quot;lt2&quot; tx2=&quot;dk2&quot; accent1=&quot;accent1&quot; accent2=&quot;accent2&quot; accent3=&quot;accent3&quot; accent4=&quot;accent4&quot; accent5=&quot;accent5&quot; accent6=&quot;accent6&quot; hlink=&quot;hlink&quot; folHlink=&quot;folHlink&quot;/&gt;.
        /// </summary>
        internal static string colorschememapping {
            get {
                return ResourceManager.GetString("colorschememapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;xml xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;&gt;
        /// &lt;o:MainFile HRef=&quot;../templ.htm&quot;/&gt;
        /// &lt;o:File HRef=&quot;themedata.thmx&quot;/&gt;
        /// &lt;o:File HRef=&quot;colorschememapping.xml&quot;/&gt;
        /// &lt;o:File HRef=&quot;image001.png&quot;/&gt;
        /// &lt;o:File HRef=&quot;image002.jpg&quot;/&gt;
        /// &lt;o:File HRef=&quot;filelist.xml&quot;/&gt;
        ///&lt;/xml&gt;.
        /// </summary>
        internal static string filelist {
            get {
                return ResourceManager.GetString("filelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image001 {
            get {
                object obj = ResourceManager.GetObject("image001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///xmlns:w=&quot;urn:schemas-microsoft-com:office:word&quot;
        ///xmlns:m=&quot;http://schemas.microsoft.com/office/2004/12/omml&quot;
        ///xmlns=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1250&quot;&gt;
        ///&lt;meta name=ProgId content=Word.Document&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 15&quot;&gt;
        ///&lt;meta name=Originator content=&quot;Microsoft Word 15&quot;&gt;
        ///&lt;link rel=File-List href=&quot;a_files/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string outlook_signature_template_htm {
            get {
                return ResourceManager.GetString("outlook_signature_template_htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1025\ansi\ansicpg1250\uc1\adeff31507\deff0\stshfdbch31505\stshfloch31506\stshfhich31506\stshfbi31507\deflang1038\deflangfe1038\themelang1038\themelangfe0\themelangcs0{\fonttbl{\f0\fbidi \froman\fcharset238\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\fbidi \fswiss\fcharset238\fprq2{\*\panose 020b0604020202020204}Arial;}
        ///{\f20\fbidi \froman\fcharset129\fprq1{\*\panose 020b0600000101010101}Gulim{\*\falt \&apos;b1\&apos;bc\&apos;b8\&apos;b2};}{\f34\fbidi \froman\fcharset0\fprq2{\*\panose 020405030504 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string outlook_signature_template_rtf {
            get {
                return ResourceManager.GetString("outlook_signature_template_rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to           ///%greeting%,        ///        ///        ///%name%
        ///%position% | %department%
        ///
        ///Hanon Systems Hungary. Kft
        ///8000 Székesfehérvár, Aszalvölgyi út 9-11.
        ///T +36 20 %phone%     M %mobile%
        ///%cdsid%@hanonsystems.com
        ///www.hanonsystems.com        ///        ///        ///
        ///CONFIDENTIALITY NOTICE: This e-mail message including attachments, if any, is intended only for the person or entity to which it is addressed and may contain confidential and /or privileged material. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended rec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string outlook_signature_template_txt {
            get {
                return ResourceManager.GetString("outlook_signature_template_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] themedata {
            get {
                object obj = ResourceManager.GetObject("themedata", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
